service: screenshot-as-a-service

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 2536
    timeout: 180
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "s3:upload"
          Resource: "arn:aws:s3:::techletter.app/*"

functions:
    screenshot-function:
        handler: src/index.handler
        environment:
            DEBUG: 0
        events:
            - http:
                  path: screenshot
                  method: GET
                  cors: true

package:
    exclude:
        - node_modules/puppeteer/.local-chromium/**

plugins:
    - serverless-plugin-chrome

custom:
    chrome:
        flags:
            - --window-size=1280,1696 # Letter size
            - --hide-scrollbars
            - --ignore-certificate-errors
        functions:
            - screenshot-function
