service: screenshot-as-a-service

provider:
    name: aws
    stage: dev2
    runtime: nodejs14.x
    memorySize: 2560
    timeout: 30
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "s3:*"
          Resource: "arn:aws:s3:::techletter.app/*"

functions:
    embeds:
        handler: dist/embeds.handler
        events:
            - http:
                  path: embed
                  method: GET
                  cors: true
    code:
        handler: dist/code.handler
        events:
            - http:
                  path: code
                  method: GET
                  cors: true

    image:
        handler: dist/optimizeImage.handler
        events:
            - http:
                  path: image
                  method: GET
                  cors: true
                  
    socialCard:
        handler: dist/socialCard.handler
        events:
            - http:
                path: social-card
                method: GET
                cors: true

package:
    include:
        - dist/**
    exclude:
        - node_modules/puppeteer/.local-chromium/**
