service: screenshot-as-a-service

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 2536
    timeout: 30
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "s3:upload"
          Resource: "arn:aws:s3:::techletter.app/*"

functions:
    screenshot-function:
        handler: dist/index.handler
        events:
            - http:
                  path: screenshot
                  method: GET
                  cors: true

package:
    include:
        - dist/**
    exclude:
        - node_modules/puppeteer/.local-chromium/**
